version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: medusa-server-default
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://redis
      NODE_ENV: development
      JWT_SECRET: something
      COOKIE_SECRET: something
      PORT: 9000
      S3_URL: ${S3_URL}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"
    volumes:
      - .:/app/medusa
      - node_modules:/app/medusa/node_modules

  admin:
    build:
      context: ./medusa-admin
      dockerfile: Dockerfile
    image: medusa-admin:latest
    ports:
      - "7001:80"

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
    volumes: 
      - db:/var/lib/postgresql/data

  # redis:
  #   image: redis
  #   expose:
  #     - 6379

volumes:
  node_modules:
  db:
